//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace noble.coder.pweatherby.ClassCalendarSvc.ValetStand {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AppUserName", Namespace="http://schemas.datacontract.org/2004/07/noble.coder.pweatherby.AppValet")]
    [System.SerializableAttribute()]
    public partial class AppUserName : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValetKeyStatus", Namespace="http://schemas.datacontract.org/2004/07/noble.coder.pweatherby.AppValet")]
    public enum ValetKeyStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Active = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Inactive = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Blocked = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ValetStand.IAttendant")]
    public interface IAttendant {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAttendant/GetUserName", ReplyAction="http://tempuri.org/IAttendant/GetUserNameResponse")]
        noble.coder.pweatherby.ClassCalendarSvc.ValetStand.AppUserName GetUserName(string DeviceID, string ValetKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAttendant/GetUserID", ReplyAction="http://tempuri.org/IAttendant/GetUserIDResponse")]
        string GetUserID(string DeviceID, string ValetKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAttendant/GetKeyStatus", ReplyAction="http://tempuri.org/IAttendant/GetKeyStatusResponse")]
        noble.coder.pweatherby.ClassCalendarSvc.ValetStand.ValetKeyStatus GetKeyStatus(string DeviceID, string ValetKey);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAttendantChannel : noble.coder.pweatherby.ClassCalendarSvc.ValetStand.IAttendant, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AttendantClient : System.ServiceModel.ClientBase<noble.coder.pweatherby.ClassCalendarSvc.ValetStand.IAttendant>, noble.coder.pweatherby.ClassCalendarSvc.ValetStand.IAttendant {
        
        public AttendantClient() {
        }
        
        public AttendantClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AttendantClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AttendantClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AttendantClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public noble.coder.pweatherby.ClassCalendarSvc.ValetStand.AppUserName GetUserName(string DeviceID, string ValetKey) {
            return base.Channel.GetUserName(DeviceID, ValetKey);
        }
        
        public string GetUserID(string DeviceID, string ValetKey) {
            return base.Channel.GetUserID(DeviceID, ValetKey);
        }
        
        public noble.coder.pweatherby.ClassCalendarSvc.ValetStand.ValetKeyStatus GetKeyStatus(string DeviceID, string ValetKey) {
            return base.Channel.GetKeyStatus(DeviceID, ValetKey);
        }
    }
}
